# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\He3Control\trunk\He3ControlV06\aoControl.ui'
#
# Created: Fri Mar 18 16:11:28 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AoControl(object):
    def setupUi(self, AoControl):
        AoControl.setObjectName("AoControl")
        AoControl.resize(626, 114)
        self.horizontalLayoutWidget = QtGui.QWidget(AoControl)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 611, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.slide = QtGui.QSlider(self.horizontalLayoutWidget)
        self.slide.setOrientation(QtCore.Qt.Horizontal)
        self.slide.setObjectName("slide")
        self.gridLayout.addWidget(self.slide, 0, 3, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.horizontalLayoutWidget)
        self.progressBar.setProperty("value", QtCore.QVariant(24))
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 3, 1, 1)
        self.buttonLeft = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLeft.sizePolicy().hasHeightForWidth())
        self.buttonLeft.setSizePolicy(sizePolicy)
        self.buttonLeft.setObjectName("buttonLeft")
        self.gridLayout.addWidget(self.buttonLeft, 0, 0, 1, 1)
        self.leftSlow = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftSlow.sizePolicy().hasHeightForWidth())
        self.leftSlow.setSizePolicy(sizePolicy)
        self.leftSlow.setObjectName("leftSlow")
        self.gridLayout.addWidget(self.leftSlow, 1, 0, 1, 1)
        self.buttonRight = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRight.sizePolicy().hasHeightForWidth())
        self.buttonRight.setSizePolicy(sizePolicy)
        self.buttonRight.setObjectName("buttonRight")
        self.gridLayout.addWidget(self.buttonRight, 0, 1, 1, 1)
        self.rightSlow = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightSlow.sizePolicy().hasHeightForWidth())
        self.rightSlow.setSizePolicy(sizePolicy)
        self.rightSlow.setObjectName("rightSlow")
        self.gridLayout.addWidget(self.rightSlow, 1, 1, 1, 1)
        self.setPoint = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setPoint.sizePolicy().hasHeightForWidth())
        self.setPoint.setSizePolicy(sizePolicy)
        self.setPoint.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.setPoint.setDecimals(3)
        self.setPoint.setObjectName("setPoint")
        self.gridLayout.addWidget(self.setPoint, 0, 2, 1, 1)
        self.currentPoint = QtGui.QLCDNumber(self.horizontalLayoutWidget)
        self.currentPoint.setObjectName("currentPoint")
        self.gridLayout.addWidget(self.currentPoint, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.setStretch(0, 10)
        self.checkBox = QtGui.QCheckBox(AoControl)
        self.checkBox.setGeometry(QtCore.QRect(30, 90, 101, 18))
        self.checkBox.setObjectName("checkBox")
        self.slewRate = QtGui.QDoubleSpinBox(AoControl)
        self.slewRate.setGeometry(QtCore.QRect(120, 90, 62, 22))
        self.slewRate.setObjectName("slewRate")

        self.retranslateUi(AoControl)
        QtCore.QMetaObject.connectSlotsByName(AoControl)

    def retranslateUi(self, AoControl):
        AoControl.setWindowTitle(QtGui.QApplication.translate("AoControl", "AoControl", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLeft.setText(QtGui.QApplication.translate("AoControl", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.leftSlow.setText(QtGui.QApplication.translate("AoControl", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRight.setText(QtGui.QApplication.translate("AoControl", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.rightSlow.setText(QtGui.QApplication.translate("AoControl", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("AoControl", "max slew rate", None, QtGui.QApplication.UnicodeUTF8))

