
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\He3Control\trunk\He3ControlV06\UI_FitterParams.ui'
#
# Created: Sat Apr 16 01:40:38 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\He3Control\trunk\He3ControlV06\UI_FitterParams.ui'
#
# Created: Sat Apr 16 01:44:19 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_FitterWin(object):
    def setupUi(self, FitterWin):
        FitterWin.setObjectName("FitterWin")
        FitterWin.resize(672, 201)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FitterWin.sizePolicy().hasHeightForWidth())
        FitterWin.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtGui.QWidget(FitterWin)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 638, 201))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 2)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 6, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 7, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 8, 1, 1)
        self.button_plot_guess = QtGui.QCheckBox(self.gridLayoutWidget)
        self.button_plot_guess.setObjectName("button_plot_guess")
        self.gridLayout.addWidget(self.button_plot_guess, 0, 2, 1, 1)
        self.label_current = QtGui.QLabel(self.gridLayoutWidget)
        self.label_current.setObjectName("label_current")
        self.gridLayout.addWidget(self.label_current, 0, 0, 1, 2)
        self.button_all_free = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_all_free.setMaximumSize(QtCore.QSize(30, 16777215))
        self.button_all_free.setObjectName("button_all_free")
        self.gridLayout.addWidget(self.button_all_free, 0, 5, 1, 1)
        self.button_all_fixed = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_all_fixed.setMaximumSize(QtCore.QSize(30, 16777215))
        self.button_all_fixed.setObjectName("button_all_fixed")
        self.gridLayout.addWidget(self.button_all_fixed, 0, 4, 1, 1)
        self.buttonFit = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonFit.setObjectName("buttonFit")
        self.gridLayout.addWidget(self.buttonFit, 0, 3, 1, 1)
        self.button_take_all = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_take_all.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_take_all.setObjectName("button_take_all")
        self.gridLayout.addWidget(self.button_take_all, 0, 7, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_all_guess = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_all_guess.setMaximumSize(QtCore.QSize(30, 16777215))
        self.button_all_guess.setObjectName("button_all_guess")
        self.horizontalLayout_2.addWidget(self.button_all_guess)
        self.button_do_guess = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_do_guess.setMaximumSize(QtCore.QSize(55, 16777215))
        self.button_do_guess.setObjectName("button_do_guess")
        self.horizontalLayout_2.addWidget(self.button_do_guess)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 6, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_error = QtGui.QLabel(self.gridLayoutWidget)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout.addWidget(self.label_error)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_noInterrupt = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_noInterrupt.setObjectName("radioButton_noInterrupt")
        self.verticalLayout_3.addWidget(self.radioButton_noInterrupt)
        self.radioButton_stopIfError = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_stopIfError.setObjectName("radioButton_stopIfError")
        self.verticalLayout_3.addWidget(self.radioButton_stopIfError)
        self.radioButton_stopAnyWay = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_stopAnyWay.setObjectName("radioButton_stopAnyWay")
        self.verticalLayout_3.addWidget(self.radioButton_stopAnyWay)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 8, 1, 1)

        self.retranslateUi(FitterWin)
        QtCore.QMetaObject.connectSlotsByName(FitterWin)

    def retranslateUi(self, FitterWin):
        FitterWin.setWindowTitle(QtGui.QApplication.translate("FitterWin", "parameters for fit ...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FitterWin", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FitterWin", "val. fitted", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FitterWin", "guess val.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FitterWin", "fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FitterWin", "free", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FitterWin", "guess (+free)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FitterWin", "take last value", None, QtGui.QApplication.UnicodeUTF8))
        self.button_plot_guess.setText(QtGui.QApplication.translate("FitterWin", "plot guess", None, QtGui.QApplication.UnicodeUTF8))
        self.label_current.setText(QtGui.QApplication.translate("FitterWin", "current curve", None, QtGui.QApplication.UnicodeUTF8))
        self.button_all_free.setText(QtGui.QApplication.translate("FitterWin", "all!", None, QtGui.QApplication.UnicodeUTF8))
        self.button_all_fixed.setText(QtGui.QApplication.translate("FitterWin", "all!", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFit.setText(QtGui.QApplication.translate("FitterWin", "fit!", None, QtGui.QApplication.UnicodeUTF8))
        self.button_take_all.setText(QtGui.QApplication.translate("FitterWin", "all off", None, QtGui.QApplication.UnicodeUTF8))
        self.button_all_guess.setText(QtGui.QApplication.translate("FitterWin", "all!", None, QtGui.QApplication.UnicodeUTF8))
        self.button_do_guess.setText(QtGui.QApplication.translate("FitterWin", "do guess!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_error.setText(QtGui.QApplication.translate("FitterWin", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_noInterrupt.setText(QtGui.QApplication.translate("FitterWin", "no interrupt", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_stopIfError.setText(QtGui.QApplication.translate("FitterWin", "stop if error", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_stopAnyWay.setText(QtGui.QApplication.translate("FitterWin", "stop anyway", None, QtGui.QApplication.UnicodeUTF8))

