# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\He3Control\trunk\He3ControlV06\UI_plot.ui'
#
# Created: Thu Apr 21 20:03:22 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 726)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = MplWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.x1_label = QtGui.QLabel(self.centralwidget)
        self.x1_label.setObjectName("x1_label")
        self.gridLayout.addWidget(self.x1_label, 1, 0, 1, 1)
        self.x1 = QtGui.QLabel(self.centralwidget)
        self.x1.setObjectName("x1")
        self.gridLayout.addWidget(self.x1, 1, 1, 1, 1)
        self.x2_label = QtGui.QLabel(self.centralwidget)
        self.x2_label.setObjectName("x2_label")
        self.gridLayout.addWidget(self.x2_label, 1, 2, 1, 1)
        self.x2 = QtGui.QLabel(self.centralwidget)
        self.x2.setObjectName("x2")
        self.gridLayout.addWidget(self.x2, 1, 3, 1, 1)
        self.diffx_label = QtGui.QLabel(self.centralwidget)
        self.diffx_label.setObjectName("diffx_label")
        self.gridLayout.addWidget(self.diffx_label, 1, 4, 1, 1)
        self.y1_label = QtGui.QLabel(self.centralwidget)
        self.y1_label.setObjectName("y1_label")
        self.gridLayout.addWidget(self.y1_label, 3, 0, 1, 1)
        self.y1 = QtGui.QLabel(self.centralwidget)
        self.y1.setObjectName("y1")
        self.gridLayout.addWidget(self.y1, 3, 1, 1, 1)
        self.y2_label = QtGui.QLabel(self.centralwidget)
        self.y2_label.setObjectName("y2_label")
        self.gridLayout.addWidget(self.y2_label, 3, 2, 1, 1)
        self.y2 = QtGui.QLabel(self.centralwidget)
        self.y2.setObjectName("y2")
        self.gridLayout.addWidget(self.y2, 3, 3, 1, 1)
        self.diffy_label = QtGui.QLabel(self.centralwidget)
        self.diffy_label.setObjectName("diffy_label")
        self.gridLayout.addWidget(self.diffy_label, 3, 4, 1, 1)
        self.diffy = QtGui.QLabel(self.centralwidget)
        self.diffy.setObjectName("diffy")
        self.gridLayout.addWidget(self.diffy, 3, 5, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 7, 1, 1)
        self.radioButton_1 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout.addWidget(self.radioButton_1, 3, 6, 1, 1)
        self.loglinbutton = QtGui.QPushButton(self.centralwidget)
        self.loglinbutton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.loglinbutton.setObjectName("loglinbutton")
        self.gridLayout.addWidget(self.loglinbutton, 1, 9, 1, 1)
        self.buttonLegend = QtGui.QPushButton(self.centralwidget)
        self.buttonLegend.setObjectName("buttonLegend")
        self.gridLayout.addWidget(self.buttonLegend, 1, 7, 1, 1)
        self.buttonPrint = QtGui.QPushButton(self.centralwidget)
        self.buttonPrint.setObjectName("buttonPrint")
        self.gridLayout.addWidget(self.buttonPrint, 1, 6, 1, 1)
        self.diffx = QtGui.QLabel(self.centralwidget)
        self.diffx.setObjectName("diffx")
        self.gridLayout.addWidget(self.diffx, 1, 5, 1, 1)
        self.loglinbutton_x = QtGui.QPushButton(self.centralwidget)
        self.loglinbutton_x.setMaximumSize(QtCore.QSize(40, 16777215))
        self.loglinbutton_x.setObjectName("loglinbutton_x")
        self.gridLayout.addWidget(self.loglinbutton_x, 1, 8, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 3, 8, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_last = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_last.setObjectName("spinBox_last")
        self.horizontalLayout.addWidget(self.spinBox_last)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 10, 1, 1)
        self.buttonMore = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMore.sizePolicy().hasHeightForWidth())
        self.buttonMore.setSizePolicy(sizePolicy)
        self.buttonMore.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonMore.setMaximumSize(QtCore.QSize(23, 12))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.buttonMore.setFont(font)
        self.buttonMore.setIconSize(QtCore.QSize(16, 16))
        self.buttonMore.setCheckable(False)
        self.buttonMore.setAutoExclusive(False)
        self.buttonMore.setAutoDefault(False)
        self.buttonMore.setDefault(False)
        self.buttonMore.setFlat(False)
        self.buttonMore.setObjectName("buttonMore")
        self.gridLayout.addWidget(self.buttonMore, 1, 10, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.x1_label.setText(QtGui.QApplication.translate("MainWindow", "x1 = ", None, QtGui.QApplication.UnicodeUTF8))
        self.x1.setText(QtGui.QApplication.translate("MainWindow", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.x2_label.setText(QtGui.QApplication.translate("MainWindow", "x2 = ", None, QtGui.QApplication.UnicodeUTF8))
        self.x2.setText(QtGui.QApplication.translate("MainWindow", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.diffx_label.setText(QtGui.QApplication.translate("MainWindow", "Diff_x = ", None, QtGui.QApplication.UnicodeUTF8))
        self.y1_label.setText(QtGui.QApplication.translate("MainWindow", "y1 = ", None, QtGui.QApplication.UnicodeUTF8))
        self.y1.setText(QtGui.QApplication.translate("MainWindow", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.y2_label.setText(QtGui.QApplication.translate("MainWindow", "y2 = ", None, QtGui.QApplication.UnicodeUTF8))
        self.y2.setText(QtGui.QApplication.translate("MainWindow", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.diffy_label.setText(QtGui.QApplication.translate("MainWindow", "Diff_y = ", None, QtGui.QApplication.UnicodeUTF8))
        self.diffy.setText(QtGui.QApplication.translate("MainWindow", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "let the window contain entirely (and a bit more) all plotted curves", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_1.setToolTip(QtGui.QApplication.translate("MainWindow", "autoscaling wont bother you in this case", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_1.setText(QtGui.QApplication.translate("MainWindow", "manual scaling", None, QtGui.QApplication.UnicodeUTF8))
        self.loglinbutton.setText(QtGui.QApplication.translate("MainWindow", "switch to logscale", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLegend.setText(QtGui.QApplication.translate("MainWindow", "make legend", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPrint.setToolTip(QtGui.QApplication.translate("MainWindow", "Will prompt for a filename save the pdf where you specified and open it. Press cancel in the save dialog if you just want to print...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPrint.setText(QtGui.QApplication.translate("MainWindow", "save + print", None, QtGui.QApplication.UnicodeUTF8))
        self.diffx.setText(QtGui.QApplication.translate("MainWindow", "???", None, QtGui.QApplication.UnicodeUTF8))
        self.loglinbutton_x.setText(QtGui.QApplication.translate("MainWindow", "x->log", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setToolTip(QtGui.QApplication.translate("MainWindow", "scales on last plotted curve (unless scaleOnMe is False for that curve (default = True))", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "scale on last", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "show last", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonMore.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))

from mplwidget import MplWidget
