# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\He3Control\trunk\He3ControlV06\UI_sessionManager.ui'
#
# Created: Tue Feb 08 15:10:42 2011
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_sessionManager(object):
    def setupUi(self, sessionManager):
        sessionManager.setObjectName("sessionManager")
        sessionManager.resize(504, 677)
        self.centralwidget = QtGui.QWidget(sessionManager)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditArgs = QtGui.QTextEdit(self.centralwidget)
        self.textEditArgs.setGeometry(QtCore.QRect(0, 190, 501, 131))
        self.textEditArgs.setObjectName("textEditArgs")
        self.textEditKwds = QtGui.QTextEdit(self.centralwidget)
        self.textEditKwds.setGeometry(QtCore.QRect(0, 340, 381, 131))
        self.textEditKwds.setObjectName("textEditKwds")
        self.pushButtonStart = QtGui.QPushButton(self.centralwidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(150, 490, 121, 61))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 481, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 320, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 111, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 40, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 261, 20))
        self.label_4.setObjectName("label_4")
        self.textBrowserHelp = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowserHelp.setGeometry(QtCore.QRect(0, 70, 501, 91))
        self.textBrowserHelp.setObjectName("textBrowserHelp")
        self.pushButtonPause = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPause.setGeometry(QtCore.QRect(340, 490, 71, 61))
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.pushButtonStop = QtGui.QPushButton(self.centralwidget)
        self.pushButtonStop.setGeometry(QtCore.QRect(270, 490, 71, 61))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.label_status = QtGui.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(10, 500, 131, 41))
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.pushButtonRestart = QtGui.QPushButton(self.centralwidget)
        self.pushButtonRestart.setGeometry(QtCore.QRect(410, 490, 71, 61))
        self.pushButtonRestart.setObjectName("pushButtonRestart")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 560, 171, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineSessionName = QtGui.QLineEdit(self.centralwidget)
        self.lineSessionName.setGeometry(QtCore.QRect(244, 580, 191, 20))
        self.lineSessionName.setObjectName("lineSessionName")
        self.buttonBrowse = QtGui.QPushButton(self.centralwidget)
        self.buttonBrowse.setGeometry(QtCore.QRect(10, 578, 31, 23))
        self.buttonBrowse.setObjectName("buttonBrowse")
        self.buttonCreate = QtGui.QPushButton(self.centralwidget)
        self.buttonCreate.setGeometry(QtCore.QRect(450, 579, 41, 23))
        self.buttonCreate.setObjectName("buttonCreate")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 610, 61, 20))
        self.label_6.setObjectName("label_6")
        self.labelLastSaved = QtGui.QLabel(self.centralwidget)
        self.labelLastSaved.setGeometry(QtCore.QRect(70, 610, 421, 20))
        self.labelLastSaved.setObjectName("labelLastSaved")
        self.checkBoxNewDir = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxNewDir.setEnabled(True)
        self.checkBoxNewDir.setGeometry(QtCore.QRect(10, 490, 141, 18))
        self.checkBoxNewDir.setChecked(True)
        self.checkBoxNewDir.setObjectName("checkBoxNewDir")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(191, 557, 131, 20))
        self.label_8.setObjectName("label_8")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(330, 558, 151, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.labelSaveDir = QtGui.QLabel(self.centralwidget)
        self.labelSaveDir.setGeometry(QtCore.QRect(50, 580, 191, 20))
        self.labelSaveDir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelSaveDir.setObjectName("labelSaveDir")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(240, 580, 16, 20))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setObjectName("label_9")
        self.pushButton_useLast = QtGui.QPushButton(self.centralwidget)
        self.pushButton_useLast.setGeometry(QtCore.QRect(390, 350, 101, 31))
        self.pushButton_useLast.setObjectName("pushButton_useLast")
        self.pushButton_useDefault = QtGui.QPushButton(self.centralwidget)
        self.pushButton_useDefault.setGeometry(QtCore.QRect(390, 390, 101, 31))
        self.pushButton_useDefault.setObjectName("pushButton_useDefault")
        self.pushButton_setLast = QtGui.QPushButton(self.centralwidget)
        self.pushButton_setLast.setGeometry(QtCore.QRect(390, 430, 101, 31))
        self.pushButton_setLast.setObjectName("pushButton_setLast")
        sessionManager.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(sessionManager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuVariables = QtGui.QMenu(self.menubar)
        self.menuVariables.setObjectName("menuVariables")
        sessionManager.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(sessionManager)
        self.statusbar.setObjectName("statusbar")
        sessionManager.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(sessionManager)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(sessionManager)
        self.actionSave.setObjectName("actionSave")
        self.actionReloadAllsessions = QtGui.QAction(sessionManager)
        self.actionReloadAllsessions.setObjectName("actionReloadAllsessions")
        self.actionDynamic_variables = QtGui.QAction(sessionManager)
        self.actionDynamic_variables.setObjectName("actionDynamic_variables")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReloadAllsessions)
        self.menuVariables.addAction(self.actionDynamic_variables)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuVariables.menuAction())

        self.retranslateUi(sessionManager)
        QtCore.QMetaObject.connectSlotsByName(sessionManager)

    def retranslateUi(self, sessionManager):
        sessionManager.setWindowTitle(QtGui.QApplication.translate("sessionManager", "sessionManager", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStart.setText(QtGui.QApplication.translate("sessionManager", "START!", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("sessionManager", "keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("sessionManager", "args", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("sessionManager", "session", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("sessionManager", "help", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPause.setText(QtGui.QApplication.translate("sessionManager", "PAUSE", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStop.setText(QtGui.QApplication.translate("sessionManager", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("sessionManager", "session stopped", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRestart.setText(QtGui.QApplication.translate("sessionManager", "RESTART", None, QtGui.QApplication.UnicodeUTF8))
        self.lineSessionName.setText(QtGui.QApplication.translate("sessionManager", "toroid8", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBrowse.setText(QtGui.QApplication.translate("sessionManager", "(...)", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCreate.setText(QtGui.QApplication.translate("sessionManager", "create", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("sessionManager", "last saved :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLastSaved.setText(QtGui.QApplication.translate("sessionManager", "M:/Samples/wafer11/toroid8/003_mode1_cal_5mV", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNewDir.setText(QtGui.QApplication.translate("sessionManager", "new dir on startup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("sessionManager", "manual directory operation", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSaveDir.setText(QtGui.QApplication.translate("sessionManager", "\"today directory\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("sessionManager", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_useLast.setText(QtGui.QApplication.translate("sessionManager", "Use last", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_useDefault.setText(QtGui.QApplication.translate("sessionManager", "Use default", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_setLast.setText(QtGui.QApplication.translate("sessionManager", "Set as last", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("sessionManager", "file", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVariables.setTitle(QtGui.QApplication.translate("sessionManager", "variables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("sessionManager", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("sessionManager", "save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadAllsessions.setText(QtGui.QApplication.translate("sessionManager", "reload all sessions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDynamic_variables.setText(QtGui.QApplication.translate("sessionManager", "dynamic variables", None, QtGui.QApplication.UnicodeUTF8))

